### PR TITLE
added treasury module @95% coverage

### PR DESCRIPTION
**Pull request by jordaniza**
@Chiptuttofuso here is the PR off master.

### CODE REVIEW

**Comment by Chiptuttofuso** [comment]
@jordaniza tests are failing in 3 cases, i will attach the logs here

`> piedao-backend@0.0.1 test
> jest --detectOpenHandles --forceExit "src/treasury"

 FAIL  src/treasury/test/treasury.service.spec.ts (5.326 s)
  ● Testing the treasury service › Saves the model in the db

    expect(received).toEqual(expected) // deep equality

    Expected: {"assets": 100, "debt": 0, "network": "ethereum", "protocol": "aave", "total": 100}
    Received: [{"__v": 0, "_id": "61694bf86152245b3a3abcad", "assets": 100, "createdAt": 2021-10-15T09:38:00.921Z, "debt": 0, "network": "ethereum", "protocol": "aave", "total": 100, "updatedAt": 2021-10-15T09:38:00.921Z}, {"__v": 0, "_id": "61694d6dc7160e5c53219bd1", "assets": 100, "createdAt": 2021-10-15T09:44:13.632Z, "debt": 0, "network": "ethereum", "protocol": "aave", "total": 100, "updatedAt": 2021-10-15T09:44:13.632Z}]

      124 |     await service.loadDB(recordMockValue);
      125 |     const recordAfter = await service.treasuryModel.find();
    > 126 |     expect(recordAfter).toEqual(recordMockValue);
          |                         ^
      127 |     expect(recordBefore).toBeUndefined();
      128 |   });
      129 |

      at Object.<anonymous> (treasury/test/treasury.service.spec.ts:126:25)

  ● Testing the treasury service › Rejects a model with a missing field

    expect(received).toEqual(expected) // deep equality

    Expected: 0
    Received: 1

      129 |
      130 |   it('Rejects a model with a missing field', async () => {
    > 131 |     expect(1).toEqual(0);
          |               ^
      132 |   });
      133 |
      134 |   it('Returns a treasury record if we have an array of values returned', async () => {

      at Object.<anonymous> (treasury/test/treasury.service.spec.ts:131:15)

  ● Testing the treasury service › Returns a treasury values object when passed in a valid balance

    TypeError: Cannot destructure property 'meta' of 'balance[this.treasury]' as it is undefined.

      124 |      * @returns an object containing the USD values mapped to lower case keys, for loading to the DB
      125 |      */
    > 126 |     const { meta } = balance[this.treasury];
          |             ^
      127 |     if (meta && meta.length > 0) {
      128 |       const labels: MetaLabel[] = ['Assets', 'Debt', 'Total'];
      129 |       const treasuryArray = labels.map((label) =>

      at TreasuryService.extractTreasuryValues (treasury/treasury.service.ts:126:13)
      at Object.<anonymous> (treasury/test/treasury.service.spec.ts:161:36)

 PASS  src/treasury/test/supportedNetwork.dto.spec.ts
 PASS  src/treasury/test/treasury.dto.spec.ts
 PASS  src/treasury/test/treasury.module.spec.ts
 PASS  src/treasury/test/treasury.controller.spec.ts

Test Suites: 1 failed, 4 passed, 5 total
Tests:       3 failed, 14 passed, 17 total
Snapshots:   0 total
Time:        6.005 s, estimated 13 s
Ran all test suites matching /src\/treasury/i.`

**Comment by jordaniza** [comment]
@Chiptuttofuso I've added the following changes:

- Coverage for treasury module is at 100%
- Cron is set to run at midnight every day
- Controller now implements a single GET route that fetches all treasury data. You can pass in a parameter `days=Whatever` to the query string to get however far back you want, it defaults to 7

Please note: you need to set 2 new env vars for the Mongo Integration test to run in treasury:

```
MONGO_DB_ROOT=mongodb://{username}:{password}@localhost:27017/
MONGO_DB_TEST_DATABASE=test
```

This is because Mongoose appears to have difficulties connecting to the test database, when it is specified in a single query string, and we don't want to pollute the live DB with test values.

**Comment by Chiptuttofuso** [comment]
> @Chiptuttofuso I've added the following changes:
> 
> * Coverage for treasury module is at 100%
> * Cron is set to run at midnight every day
> * Controller now implements a single GET route that fetches all treasury data. You can pass in a parameter `days=Whatever` to the query string to get however far back you want, it defaults to 7
> 
> Please note: you need to set 2 new env vars for the Mongo Integration test to run in treasury:
> 
> ```
> MONGO_DB_ROOT=mongodb://{username}:{password}@localhost:27017/
> MONGO_DB_TEST_DATABASE=test
> ```
> 
> This is because Mongoose appears to have difficulties connecting to the test database, when it is specified in a single query string, and we don't want to pollute the live DB with test values.

modifying the env file when not strictly needed is not really a good approach.
We won't risk any production-db pollution at all, because in the prodution-env file we have 2 variables, MONGO_DB and MONGO_DB_TEST. You don't have the MONGO_DB in your local env file because we do not expose access to our production-db for security reason.

I can tell that it works 100% without the need of splitting those 2 variables, as you can see in this example, taken from src/staking/test/staking.service.spec.ts

`  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [StakingService],
      imports: [
        HttpModule,
        ConfigModule.forRoot(),
        ScheduleModule.forRoot(),        
        MongooseModule.forRoot(process.env.MONGO_DB_TEST),
        MongooseModule.forFeature([{ name: EpochEntity.name, schema: EpochSchema }])
      ],      
    }).compile();

    service = module.get<StakingService>(StakingService);
  });`
  
  So please fix it, i'll have a look at all the rest meanwhile!

**Review by dantop114 — APPROVED** [review]
lgtm

**Pull request merged**
